In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pandas_profiling import ProfileReport
! pip install pandas-profiling

# muestra el total de las columnas de un dataset
pd.set_option('display.max_columns', None)

Requirement already satisfied: pandas-profiling in c:\users\utente\anaconda3\lib\site-packages (3.1.0)
Requirement already satisfied: requests>=2.24.0 in c:\users\utente\anaconda3\lib\site-packages (from pandas-profiling) (2.27.1)
Requirement already satisfied: seaborn>=0.10.1 in c:\users\utente\anaconda3\lib\site-packages (from pandas-profiling) (0.11.1)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in c:\users\utente\anaconda3\lib\site-packages (from pandas-profiling) (1.0.5)
Requirement already satisfied: numpy>=1.16.0 in c:\users\utente\anaconda3\lib\site-packages (from pandas-profiling) (1.19.1)
Collecting joblib~=1.0.1
  Downloading joblib-1.0.1-py3-none-any.whl (303 kB)
Requirement already satisfied: markupsafe~=2.0.1 in c:\users\utente\anaconda3\lib\site-packages (from pandas-profiling) (2.0.1)
Requirement already satisfied: matplotlib>=3.2.0 in c:\users\utente\anaconda3\lib\site-packages (from pandas-profiling) (3.3.4)
Requirement already satisfied: scipy>=1.4.1 in c:\users\utente\anaconda3\lib\site-packages (from pandas-profiling) (1.5.4)
Requirement already satisfied: PyYAML>=5.0.0 in c:\users\utente\anaconda3\lib\site-packages (from pandas-profiling) (5.3.1)
Requirement already satisfied: missingno>=0.4.2 in c:\users\utente\anaconda3\lib\site-packages (from pandas-profiling) (0.4.2)
Requirement already satisfied: tangled-up-in-unicode==0.1.0 in c:\users\utente\anaconda3\lib\site-packages (from pandas-profiling) (0.1.0)
Requirement already satisfied: tqdm>=4.48.2 in c:\users\utente\anaconda3\lib\site-packages (from pandas-profiling) (4.56.0)
Requirement already satisfied: multimethod>=1.4 in c:\users\utente\anaconda3\lib\site-packages (from pandas-profiling) (1.6)
Requirement already satisfied: visions[type_image_path]==0.7.4 in c:\users\utente\anaconda3\lib\site-packages (from pandas-profiling) (0.7.4)
Requirement already satisfied: jinja2>=2.11.1 in c:\users\utente\anaconda3\lib\site-packages (from pandas-profiling) (2.11.3)
Requirement already satisfied: phik>=0.11.1 in c:\users\utente\anaconda3\lib\site-packages (from pandas-profiling) (0.12.0)
Requirement already satisfied: pydantic>=1.8.1 in c:\users\utente\anaconda3\lib\site-packages (from pandas-profiling) (1.8.2)
Requirement already satisfied: htmlmin>=0.1.12 in c:\users\utente\anaconda3\lib\site-packages (from pandas-profiling) (0.1.12)
Requirement already satisfied: attrs>=19.3.0 in c:\users\utente\anaconda3\lib\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (20.3.0)
Requirement already satisfied: networkx>=2.4 in c:\users\utente\anaconda3\lib\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (2.5)
Requirement already satisfied: Pillow in c:\users\utente\anaconda3\lib\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (8.2.0)
Requirement already satisfied: imagehash in c:\users\utente\anaconda3\lib\site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (4.2.1)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\utente\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (2.8.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\utente\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (2.4.7)
Requirement already satisfied: cycler>=0.10 in c:\users\utente\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\utente\anaconda3\lib\site-packages (from matplotlib>=3.2.0->pandas-profiling) (1.3.1)
Requirement already satisfied: six in c:\users\utente\anaconda3\lib\site-packages (from cycler>=0.10->matplotlib>=3.2.0->pandas-profiling) (1.15.0)
Requirement already satisfied: decorator>=4.3.0 in c:\users\utente\anaconda3\lib\site-packages (from networkx>=2.4->visions[type_image_path]==0.7.4->pandas-profiling) (5.0.6)
Requirement already satisfied: pytz>=2017.2 in c:\users\utente\anaconda3\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3->pandas-profiling) (2021.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\utente\anaconda3\lib\site-packages (from pydantic>=1.8.1->pandas-profiling) (3.7.4.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\utente\anaconda3\lib\site-packages (from requests>=2.24.0->pandas-profiling) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\utente\anaconda3\lib\site-packages (from requests>=2.24.0->pandas-profiling) (1.26.4)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\utente\anaconda3\lib\site-packages (from requests>=2.24.0->pandas-profiling) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in c:\users\utente\anaconda3\lib\site-packages (from requests>=2.24.0->pandas-profiling) (2.10)
Requirement already satisfied: PyWavelets in c:\users\utente\anaconda3\lib\site-packages (from imagehash->visions[type_image_path]==0.7.4->pandas-profiling) (1.1.1)
Installing collected packages: joblib
  Attempting uninstall: joblib
    Found existing installation: joblib 1.0.0
    Uninstalling joblib-1.0.0:
      Successfully uninstalled joblib-1.0.0
Successfully installed joblib-1.0.1

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lazypredict 0.2.9 requires joblib==1.0.0, but you have joblib 1.0.1 which is incompatible.
dtale 1.61.1 requires packaging<=21.0; python_version >= "3.0", but you have packaging 21.3 which is incompatible.
dtale 1.61.1 requires scikit-learn==0.24.2; python_version > "3.0", but you have scikit-learn 0.23.1 which is incompatible.

In [3]:
df = pd.read_csv("./train.csv",sep=",")
df.head(1)
#C:\Users\Utente\Desktop\Bootcamp\01 Pandas\carpeta\Mascotas

,Type,Name,Age,Breed1,Breed2,Gender,Color1,Color2,Color3,MaturitySize,FurLength,Vaccinated,Dewormed,Sterilized,Health,Quantity,Fee,State,RescuerID,VideoAmt,Description,PetID,PhotoAmt,AdoptionSpeed
0,2,Nibble,3,299,0,1,1,7,0,1,1,2,2,2,1,1,100,41326,8480853f516546f6cf33aa88cd76c379,0,Nibble is a 3+ month old ball of cuteness. He ...,86e1089a3,1.0,2

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14993 entries, 0 to 14992
Data columns (total 24 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Type           14993 non-null  int64
 1   Name           13736 non-null  object
 2   Age            14993 non-null  int64
 3   Breed1         14993 non-null  int64
 4   Breed2         14993 non-null  int64
 5   Gender         14993 non-null  int64
 6   Color1         14993 non-null  int64
 7   Color2         14993 non-null  int64
 8   Color3         14993 non-null  int64
 9   MaturitySize   14993 non-null  int64
 10  FurLength      14993 non-null  int64
 11  Vaccinated     14993 non-null  int64
 12  Dewormed       14993 non-null  int64
 13  Sterilized     14993 non-null  int64
 14  Health         14993 non-null  int64
 15  Quantity       14993 non-null  int64
 16  Fee            14993 non-null  int64
 17  State          14993 non-null  int64
 18  RescuerID      14993 non-null  object
 19  VideoAmt       14993 non-null  int64
 20  Description    14981 non-null  object
 21  PetID          14993 non-null  object
 22  PhotoAmt       14993 non-null  float64
 23  AdoptionSpeed  14993 non-null  int64
dtypes: float64(1), int64(19), object(4)
memory usage: 2.7+ MB

In [5]:
#Hacemos un pandas profiling

In [6]:
#from pandas_profiling import ProfileReport

#prof = ProfileReport(df)

In [7]:
#automatico = ProfileReport(df) #,minimal=True)
#nombre_salida = 'EDA_Mascotas'
#automatico.to_file(output_file=nombre_salida)

In [8]:
#Vaccinated, Dewormed, Sterilized, quale delle tre è quella più relazionato con l'obiettivo. quella più relazionata si mantiene, le altre due si fa un'altra colonna con la media delle due

In [9]:
correlacion = df.corr()
correlacion

,Type,Age,Breed1,Breed2,Gender,Color1,Color2,Color3,MaturitySize,FurLength,Vaccinated,Dewormed,Sterilized,Health,Quantity,Fee,State,VideoAmt,PhotoAmt,AdoptionSpeed
Type,1.000000,-0.147162,0.057724,-0.043568,0.060843,0.097680,0.246333,0.201693,-0.171811,0.003036,0.102907,0.025508,0.006737,-0.006864,0.036423,-0.042134,0.124549,-0.005967,0.049368,-0.091240
Age,-0.147162,1.000000,-0.314346,-0.041010,-0.123423,0.090378,-0.039427,-0.053546,0.093673,0.153092,-0.136061,-0.053360,-0.189450,0.103215,-0.113076,0.089168,0.024523,-0.015969,-0.084778,0.100510
Breed1,0.057724,-0.314346,1.000000,-0.157053,0.071321,-0.035510,-0.007081,-0.000682,-0.010507,-0.108059,0.046518,0.013216,0.052698,-0.034893,0.090194,-0.189526,-0.026832,0.020626,0.043395,0.107834
Breed2,-0.043568,-0.041010,-0.157053,1.000000,0.056907,-0.020324,0.003015,0.035679,0.049879,0.106220,0.005638,-0.009817,-0.005989,-0.029285,0.038125,0.013508,-0.037993,0.001569,0.045953,-0.018642
Gender,0.060843,-0.123423,0.071321,0.056907,1.000000,-0.115351,0.026507,0.259309,-0.091819,-0.030404,0.078702,0.091431,0.040645,-0.045177,0.494489,-0.050491,0.002564,0.016816,0.098435,0.057622
Color1,0.097680,0.090378,-0.035510,-0.020324,-0.115351,1.000000,-0.113290,-0.282897,-0.029468,0.066967,-0.017475,-0.019318,-0.037050,0.024410,-0.116688,0.054180,0.024012,-0.006435,-0.041323,-0.044192
Color2,0.246333,-0.039427,-0.007081,0.003015,0.026507,-0.113290,1.000000,0.088742,-0.065155,-0.008764,0.026193,0.005812,0.007370,-0.004307,0.019876,-0.017308,0.026944,0.023983,0.059113,-0.038579
Color3,0.201693,-0.053546,-0.000682,0.035679,0.259309,-0.282897,0.088742,1.000000,-0.051730,0.013581,0.054053,0.048617,0.038899,-0.024782,0.272548,-0.019839,0.010554,0.019526,0.103662,-0.007014
MaturitySize,-0.171811,0.093673,-0.010507,0.049879,-0.091819,-0.029468,-0.065155,-0.051730,1.000000,0.095142,-0.087722,-0.067352,-0.066321,-0.012957,-0.042832,0.041144,-0.062584,0.017032,0.015593,0.045653
FurLength,0.003036,0.153092,-0.108059,0.106220,-0.030404,0.066967,-0.008764,0.013581,0.095142,1.000000,-0.006010,0.016463,0.032092,0.028096,-0.038388,0.159693,-0.029317,-0.014740,-0.031557,-0.091337
Vaccinated,0.102907,-0.136061,0.046518,0.005638,0.078702,-0.017475,0.026193,0.054053,-0.087722,-0.006010,1.000000,0.722596,0.471204,0.078893,0.125287,-0.121868,0.032737,-0.032685,-0.052719,-0.059043
Dewormed,0.025508,-0.053360,0.013216,-0.009817,0.091431,-0.019318,0.005812,0.048617,-0.067352,0.016463,0.722596,1.000000,0.426256,0.072188,0.141355,-0.105978,-0.001310,-0.036961,-0.099026,-0.013210
Sterilized,0.006737,-0.189450,0.052698,-0.005989,0.040645,-0.037050,0.007370,0.038899,-0.066321,0.032092,0.471204,0.426256,1.000000,0.057916,0.101919,-0.063790,0.009951,-0.018720,-0.062067,-0.083447
Health,-0.006864,0.103215,-0.034893,-0.029285,-0.045177,0.024410,-0.004307,-0.024782,-0.012957,0.028096,0.078893,0.072188,0.057916,1.000000,-0.034567,-0.010073,0.026237,-0.004984,-0.023978,0.029382
Quantity,0.036423,-0.113076,0.090194,0.038125,0.494489,-0.116688,0.019876,0.272548,-0.042832,-0.038388,0.125287,0.141355,0.101919,-0.034567,1.000000,-0.060523,-0.002182,0.008344,0.137839,0.062931
Fee,-0.042134,0.089168,-0.189526,0.013508,-0.050491,0.054180,-0.017308,-0.019839,0.041144,0.159693,-0.121868,-0.105978,-0.063790,-0.010073,-0.060523,1.000000,-0.015758,-0.000839,0.005103,-0.004017
State,0.124549,0.024523,-0.026832,-0.037993,0.002564,0.024012,0.026944,0.010554,-0.062584,-0.029317,0.032737,-0.001310,0.009951,0.026237,-0.002182,-0.015758,1.000000,-0.027456,0.001873,0.013119
VideoAmt,-0.005967,-0.015969,0.020626,0.001569,0.016816,-0.006435,0.023983,0.019526,0.017032,-0.014740,-0.032685,-0.036961,-0.018720,-0.004984,0.008344,-0.000839,-0.027456,1.000000,0.227231,-0.000571
PhotoAmt,0.049368,-0.084778,0.043395,0.045953,0.098435,-0.041323,0.059113,0.103662,0.015593,-0.031557,-0.052719,-0.099026,-0.062067,-0.023978,0.137839,0.005103,0.001873,0.227231,1.000000,-0.023233
AdoptionSpeed,-0.091240,0.100510,0.107834,-0.018642,0.057622,-0.044192,-0.038579,-0.007014,0.045653,-0.091337,-0.059043,-0.013210,-0.083447,0.029382,0.062931,-0.004017,0.013119,-0.000571,-0.023233,1.000000

In [10]:
#dejamos la columna Sterilized, por ser la columna que tiene  una mayor correlación con AdoptionSpeed

#Significado de los valores en las tres columnas: 1 = Sí, 2 = No, 3 = No estoy seguro

#Hacemos una copia por tratamiento de la nueva columna:

In [11]:
#df1=suma de las columnas Vaccinated y Dewormed
df1=df.copy()
df1.insert(11, "Vac_Dew_1", df1["Vaccinated"]+df1["Dewormed"])
df1.drop(["Vaccinated","Dewormed"],axis=1, inplace=True)
df1.head(5)

,Type,Name,Age,Breed1,Breed2,Gender,Color1,Color2,Color3,MaturitySize,FurLength,Vac_Dew_1,Sterilized,Health,Quantity,Fee,State,RescuerID,VideoAmt,Description,PetID,PhotoAmt,AdoptionSpeed
0,2,Nibble,3,299,0,1,1,7,0,1,1,4,2,1,1,100,41326,8480853f516546f6cf33aa88cd76c379,0,Nibble is a 3+ month old ball of cuteness. He ...,86e1089a3,1.0,2
1,2,No Name Yet,1,265,0,1,1,2,0,2,2,6,3,1,1,0,41401,3082c7125d8fb66f7dd4bff4192c8b14,0,I just found it alone yesterday near my apartm...,6296e909a,2.0,0
2,1,Brisco,1,307,0,1,2,7,0,2,2,2,2,1,1,0,41326,fa90fa5b1ee11c86938398b60abc32cb,0,Their pregnant mother was dumped by her irresp...,3422e4906,7.0,3
3,1,Miko,4,307,0,2,1,2,0,2,1,2,2,1,1,150,41401,9238e4f44c71a75282e62f7136c6b240,0,"Good guard dog, very alert, active, obedience ...",5842f1ff5,8.0,2
4,1,Hunter,1,307,0,1,1,0,0,2,1,4,2,1,1,0,41326,95481e953f8aed9ec3d16fc4509537e8,0,This handsome yet cute boy is up for adoption....,850a43f90,3.0,2

In [12]:
#df2=media de las columnas Vaccinated y Dewormed
df2=df.copy()
df2.insert(11, "Vac_Dew_2", (df2["Vaccinated"]+df2["Dewormed"])/2)
df2.drop(["Vaccinated","Dewormed"],axis=1, inplace=True)
df2.head(5)

,Type,Name,Age,Breed1,Breed2,Gender,Color1,Color2,Color3,MaturitySize,FurLength,Vac_Dew_2,Sterilized,Health,Quantity,Fee,State,RescuerID,VideoAmt,Description,PetID,PhotoAmt,AdoptionSpeed
0,2,Nibble,3,299,0,1,1,7,0,1,1,2.0,2,1,1,100,41326,8480853f516546f6cf33aa88cd76c379,0,Nibble is a 3+ month old ball of cuteness. He ...,86e1089a3,1.0,2
1,2,No Name Yet,1,265,0,1,1,2,0,2,2,3.0,3,1,1,0,41401,3082c7125d8fb66f7dd4bff4192c8b14,0,I just found it alone yesterday near my apartm...,6296e909a,2.0,0
2,1,Brisco,1,307,0,1,2,7,0,2,2,1.0,2,1,1,0,41326,fa90fa5b1ee11c86938398b60abc32cb,0,Their pregnant mother was dumped by her irresp...,3422e4906,7.0,3
3,1,Miko,4,307,0,2,1,2,0,2,1,1.0,2,1,1,150,41401,9238e4f44c71a75282e62f7136c6b240,0,"Good guard dog, very alert, active, obedience ...",5842f1ff5,8.0,2
4,1,Hunter,1,307,0,1,1,0,0,2,1,2.0,2,1,1,0,41326,95481e953f8aed9ec3d16fc4509537e8,0,This handsome yet cute boy is up for adoption....,850a43f90,3.0,2

In [13]:
#df3. El valor 3 de las columnas Vaccinated, Dewormed y Sterilized pasa a valer 0 y después hacemos la media de las dos primeras columnas
df3=df.copy()
df3["Vaccinated"] = df3['Vaccinated'].apply(lambda x: 0 if x==3 else x) 
df3["Dewormed"] = df3['Dewormed'].apply(lambda x: 0 if x==3 else x) 
#df3["Sterilized"] = df3['Sterilized'].apply(lambda x: 0 if x==3 else x)
df3.insert(11, "Vac_Dew_3", (df3["Vaccinated"]+df3["Dewormed"])/2)
df3.drop(["Vaccinated","Dewormed"],axis=1, inplace=True)
df3.head(5)

,Type,Name,Age,Breed1,Breed2,Gender,Color1,Color2,Color3,MaturitySize,FurLength,Vac_Dew_3,Sterilized,Health,Quantity,Fee,State,RescuerID,VideoAmt,Description,PetID,PhotoAmt,AdoptionSpeed
0,2,Nibble,3,299,0,1,1,7,0,1,1,2.0,2,1,1,100,41326,8480853f516546f6cf33aa88cd76c379,0,Nibble is a 3+ month old ball of cuteness. He ...,86e1089a3,1.0,2
1,2,No Name Yet,1,265,0,1,1,2,0,2,2,0.0,3,1,1,0,41401,3082c7125d8fb66f7dd4bff4192c8b14,0,I just found it alone yesterday near my apartm...,6296e909a,2.0,0
2,1,Brisco,1,307,0,1,2,7,0,2,2,1.0,2,1,1,0,41326,fa90fa5b1ee11c86938398b60abc32cb,0,Their pregnant mother was dumped by her irresp...,3422e4906,7.0,3
3,1,Miko,4,307,0,2,1,2,0,2,1,1.0,2,1,1,150,41401,9238e4f44c71a75282e62f7136c6b240,0,"Good guard dog, very alert, active, obedience ...",5842f1ff5,8.0,2
4,1,Hunter,1,307,0,1,1,0,0,2,1,2.0,2,1,1,0,41326,95481e953f8aed9ec3d16fc4509537e8,0,This handsome yet cute boy is up for adoption....,850a43f90,3.0,2

In [14]:
#Añadir cada una de las tres columnas "Vac_Dew" al df4
df4=df.copy()
df4.insert(11, "Vac_Dew_1", df1["Vac_Dew_1"])
df4.insert(12, "Vac_Dew_2", df2["Vac_Dew_2"])
df4.insert(13, "Vac_Dew_3", df3["Vac_Dew_3"])

In [15]:
df4.head(5)

,Type,Name,Age,Breed1,Breed2,Gender,Color1,Color2,Color3,MaturitySize,FurLength,Vac_Dew_1,Vac_Dew_2,Vac_Dew_3,Vaccinated,Dewormed,Sterilized,Health,Quantity,Fee,State,RescuerID,VideoAmt,Description,PetID,PhotoAmt,AdoptionSpeed
0,2,Nibble,3,299,0,1,1,7,0,1,1,4,2.0,2.0,2,2,2,1,1,100,41326,8480853f516546f6cf33aa88cd76c379,0,Nibble is a 3+ month old ball of cuteness. He ...,86e1089a3,1.0,2
1,2,No Name Yet,1,265,0,1,1,2,0,2,2,6,3.0,0.0,3,3,3,1,1,0,41401,3082c7125d8fb66f7dd4bff4192c8b14,0,I just found it alone yesterday near my apartm...,6296e909a,2.0,0
2,1,Brisco,1,307,0,1,2,7,0,2,2,2,1.0,1.0,1,1,2,1,1,0,41326,fa90fa5b1ee11c86938398b60abc32cb,0,Their pregnant mother was dumped by her irresp...,3422e4906,7.0,3
3,1,Miko,4,307,0,2,1,2,0,2,1,2,1.0,1.0,1,1,2,1,1,150,41401,9238e4f44c71a75282e62f7136c6b240,0,"Good guard dog, very alert, active, obedience ...",5842f1ff5,8.0,2
4,1,Hunter,1,307,0,1,1,0,0,2,1,4,2.0,2.0,2,2,2,1,1,0,41326,95481e953f8aed9ec3d16fc4509537e8,0,This handsome yet cute boy is up for adoption....,850a43f90,3.0,2

In [17]:
df4.to_csv('mascotas_modificado')